export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const CREATE_USERS_REQUEST = "CREATE_USERS_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USERS_ERROR = "CREATE_USERS_ERROR";
